library(Matrix)

# this scripts reads the filtered_feature_bc_matrix generated by Cellranger Count
# and generates the feature_count matrix and save it in RData folder.

input.dir <- "../Input/compScBabesia/scRNAseqBabesia/"
count.files <- list.files(input.dir)
num.total.files <- length(count.files)

file.info <- data.frame(Species = rep("Babesia", num.total.files))

expr.list <- list()

for(i in 1:num.total.files){
  file.info$filename[i] <- count.files[i]
  cat(paste('processing file', file.info$filename[i]))
  cat('\n')
  file.dir <- paste(input.dir, file.info$filename[i], sep = "")
  matrix_dir <- paste(file.dir, "/filtered_feature_bc_matrix", sep = "")
  
  barcode.path <- paste(matrix_dir, "/barcodes.tsv.gz", sep = "")
  features.path <- paste(matrix_dir, "/features.tsv.gz", sep = "")
  matrix.path <- paste(matrix_dir, "/matrix.mtx.gz", sep = "")
  
  mat <- readMM(file = matrix.path)
  
  feature.names = read.delim(features.path,
                             header = FALSE,
                             stringsAsFactors = FALSE)
  
  barcode.names = read.delim(barcode.path,
                             header = FALSE,
                             stringsAsFactors = FALSE)
  
  colnames(mat) = barcode.names$V1
  rownames(mat) = feature.names$V1
  
  expr <- as.data.frame(as.matrix(mat))
  
  expr.csv.name <- paste(file.info$filename[i], ".expr.csv", sep = "")
 write.csv(expr,paste(file.dir, expr.csv.name, sep = "/"))
  
  expr.list <- c(expr.list, list(expr))
}

names(expr.list) <- count.files
saveRDS(expr.list, "../Input/compScBabesia/RData/raw_expr_data_all_spp.RData")

